### ISSUE TITLE
Plugin doesn't load model after Carla restart.

### ISSUE THREAD

**Issue by rusk911** [mikeoliphant/neural-amp-modeler-lv2#14]
Expected behavior: load plugin into Carla, load model into plugin, save Carla's preset, close and reopen Carla, load saved Carla's preset, the sound should be the same as before closing Carla.

Actual behavior: after restarting Carla sound is always clean, I need to load the model again.

Carla v. 2.4.1
Linux Mint 20.3

**Comment by mikeoliphant** [comment]
Strange. It is working for me in Ardour. Can't think why it would work in one DAW but not another.

Can you try using another plugin that uses a path parameter with Carla and see if you have the same problem? This one, for example: https://github.com/x42/convoLV2

**Comment by rusk911** [comment]
I can confirm. NAM in Ardour is working. But in Carla no.
convoLV2 restores its state. NAM restores only volume knobs but not model file loaded.

**Comment by mikeoliphant** [comment]
I'm having a hard time reproducing, as I can't get audio working on Carla at all (on Windows - my linux environment is headless). I also haven't been able to get Carla to show me a log.

If you can manage to get the LV2 log information from Carla when saving/loading the plugin, that would be helpful.

**Comment by mikeoliphant** [comment]
I was able to find LV2 logging in Ardour, and confirm that the saving/loading path is definitely working as expected there.

**Comment by rusk911** [comment]
When opening a Carla preset log shows it's loading, but the sound is still clean.

`Mapping abstractPath 'Friedman-BE-04-full-rig-e7cd9ae7221532f339f608464532cccc.nam' relative to targetDir '/home/dima/Carla/Neural Amp Modeler'`

As you can see model loaded is high gain. I have to reopen model file to get the expected sound.
So it's a plugin bug.
I can help with debugging and testing if you don't have working Linux.
LV2 logs appeared in Carla log tab only in case I start Carla from terminal.

**Comment by rusk911** [comment]
I think the best advice you can get directly from Carla maintainer @falkTX, he did a lot for Linux sound community.

**Comment by falkTX** [comment]
on windows you can get carla logs by running it through any command-line shell.

why things dont work, cant say. But I heavily recommend to try in more than just Ardour and Carla. Sadly on Windows the lv2 host options are quite limited, and Reaper doesnt support what is needed to load files.

**Comment by falkTX** [comment]
btw, freeing the path pointers should be done with the path free extension, so that it works on windows too.
that being http://lv2plug.in/ns/ext/state#freePath

**Comment by mikeoliphant** [comment]
> btw, freeing the path pointers should be done with the path free extension, so that it works on windows too.

Thanks - saw that, but haven't had a chance to implement it yet.

And thanks for the tip on getting the Carla log window to show - that should help a lot to track this down.

**Comment by mikeoliphant** [comment]
@falkTX It looks to me like Carla might not be mapping paths correctly - at least on Windows?

When saving in Carla, I get this (the lines with "**" are lv2 logging from my plugin):

```
** calling abstract_path with: C:/Users/oliph/AppData/Roaming/GuitarSim/NAM/JCM2000Crunch.nam
[carla] File::createSymbolicLink failed, unsupported
[carla] Creating symlink for 'C:/Users/oliph/AppData/Roaming/GuitarSim/NAM/JCM2000Crunch.nam' in 'C:\Share\Audio-Video\Carla-2.5.3-win64\Carla\Carla\Neural Amp Modeler'
```

When loading back, I get:

```
[carla] Mapping abstractPath 'JCM2000Crunch.nam' relative to targetDir 'C:\Share\Audio-Video\Carla-2.5.3-win64\Carla\Carla\Neural Amp Modeler'
** result of absolute_path is C:\Share\Audio-Video\Carla-2.5.3-win64\Carla\Carla\Neural Amp Modeler\JCM2000Crunch.nam
```

It looks like Carla is maybe trying to symlink the path to a local folder, but it fails? The folder "C:\Share\Audio-Video\Carla-2.5.3-win64\Carla\Carla\Neural Amp Modeler" gets created, but there is nothing in it.

**Comment by falkTX** [comment]
right, windows doesnt support symbolic links like other OSes do, and I don't use it myself so didnt test this much or at all.
Carla relies on these symbolic links for building, since it saves a lot of space vs copying files around, but makes it a pain to build under windows too...

best to ignore lv2 path stuff on carla + windows for now, try on macOS, Linux, BSD or other non windows system if you can.

**Comment by mikeoliphant** [comment]
> By the way, second log line shows symlink path, while first one shows direct path to model file. When I open a new model not loaded yet the log shows a symlink creation on preset save:
> 
> `LV2 file path to send: '/home/dima/Neural Amp Modeler/DS1_maxg_t5-6cf8b700401406ae60ed395d030bac92.nam' Creating symlink for '/home/dima/Neural Amp Modeler/DS1_maxg_t5-6cf8b700401406ae60ed395d030bac92.nam' in '/home/dima/Carla/Neural Amp Modeler'`

@rusk911 Can you verify that the symlinks to your .nam files are getting created correctly in '/home/dima/Carla/Neural Amp Modeler'`? Thanks!

**Comment by mikeoliphant** [comment]
Ok - I think I've got this fixed. @rusk911 can you verify on your end? If nothing else, there should be a better error message on failure.

**Comment by rusk911** [comment]
> > By the way, second log line shows symlink path, while first one shows direct path to model file. When I open a new model not loaded yet the log shows a symlink creation on preset save:
> > `LV2 file path to send: '/home/dima/Neural Amp Modeler/DS1_maxg_t5-6cf8b700401406ae60ed395d030bac92.nam' Creating symlink for '/home/dima/Neural Amp Modeler/DS1_maxg_t5-6cf8b700401406ae60ed395d030bac92.nam' in '/home/dima/Carla/Neural Amp Modeler'`
> 
> @rusk911 Can you verify that the symlinks to your .nam files are getting created correctly in '/home/dima/Carla/Neural Amp Modeler'`? Thanks!

yes, symlinks are correct in Carla.

**Comment by rusk911** [comment]
> > It's working now in Carla but crashing Ardour with segfault when I try to load NAM plugin.
> 
> Hmm. It works fine in Ardour for me - but I'm running it on Windows.

Here is GDB backtrace: https://pastebin.com/1yjwU2fk

**Comment by mikeoliphant** [comment]
> Here is GDB backtrace: https://pastebin.com/1yjwU2fk

Thanks - that definitely shows the crash in the plugin state restore.

I've add a few more checks to the code to make sure the required path mapping functions are supported. Nothing that should really make a difference in this case, though, as Ardour supports them (unless maybe you're running an old version of Ardour?)

**Comment by rusk911** [comment]
Not latest, Ardour 6.9, not too old though. I'm trying to add a new
instance of plugin in a new Ardour session, i beleave there's nothing to
restore at the moment, probably this is the reason?

**Comment by mikeoliphant** [comment]
Restoring with no model shouldn't be a problem. I have no issues adding a new plugin instance to a new session in Ardour.

**Comment by rusk911** [comment]
Qtractor works, but for some reason shows 2x restore call in the log

```
Restoring model '(null)'
Missing model_Path
Restoring model '(null)'
Missing model_Path
```

**Comment by mikeoliphant** [comment]
> Audacity also doesn't want to load the plugin.

I just tested Audacity (on Windows) and it loaded the plugin fine - although Audacity (at least the version I have) does not seem to support atom:Path parameters (no way to select the model).

Just to be clear - I'm definitely not questioning that you are seeing a problem on your end. I'm just having trouble reproducing it so far.

**Comment by mikeoliphant** [comment]
> Qtractor for some reason shows 2x restore call in the log and does not restore model state after reopen.

Having multiple restores seems not uncommon, and shouldn't be a problem. The "Missing model_Path", though, indicates that the model path was not saved correctly. Anything interesting in the log when you save the plugin state?

**Comment by mikeoliphant** [comment]
> Can you try Ubuntu studio live USB stick? Both Ardour and Carla are in repos, I don't know if it's preinstalled in live image, but should be easy to install using software center. No need to install OS itself, just boot from USB stick.

I was trying to get Ardour to run under WSL. Got it working except for audio, so it won't fully start.

I'm running Linux on a Raspberry Pi, but it is headless. I've had X11 forwarding to Windows working before, though, so I should be able to get that set up.

**Comment by mikeoliphant** [comment]
Ok, I got X11 forwarding working from my Raspberry Pi.

Ardour: Plugin installs fine, but I can't interact with plugin options window (for NAM plugin, or any other). Probably an X11 forwarding bug.

Audactiy: Plugin installs fine, but Audacity doesn't support atom:Path, so I can't select a model.

**Comment by mikeoliphant** [comment]
> RPi is an ARM platform, audio things may be difficult to get to working state

I've got no issues with audio on RPi - that's what I'm using it for. I had audio issues trying to run using Windows subsystem for Linux (WSL).

**Comment by rusk911** [comment]
Just upgraded my Mint and installed Ardour 7.2. Now NAM lv2 works fine in ardour including restoring it's state. So it probably was Ardour 6.9 issue.

**Comment by mikeoliphant** [comment]
Cool - glad it is working for you!
