### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by rerdavies** [mikeoliphant/neural-amp-modeler-lv2#19]
I'd very much like to make neural-amp-modeler-lv2 available for us by PiPedal users without making them do a manual build. To that end, I need a way to include neural-amp-modeller-lv2 in a Debian package. 

The easy path for me is to bundle the nam modeler in with the PiPedal distribution. I'm doing it already with a basic starter set of 11 lv2 plugins (from the ToobAmp project). To do that, I'd have to fork, and change URLS and directories, so I don't cause installation conflicts should you ever decide to generate a debian bundle. But otherwise, it's easy.

Better, from my perspective would be to incorporate build steps for a Debian package (.deb) in your build scripts, and then either reference your project, or provide a downloadable bundle hosted by PiPedal (Already doing it with a set of Guitarix LV2 plugins that are not available by atp-get on Raspberry Pi).

I should be able to hoist the  CMake steps from PiPedal fairly easily.

A perhaps-interesting side-effect would be that it would get you 80% of the way to a Windows installer, if that interests you. Most of the heavy lifting would be done, although I have no idea where Windows LV2 files go, so you'd have to sort that out yourself.

Would you be interested in a pull request to create Debian packages?

With respect to bundling, it's unclear what your licensing state is. The right side-bar says GPL; but your project files say MIT. Bundling is out of the question if your project is GPL. My project is MIT licensed, and I do not want to be infected with GPL. As far as I can make out, all your deps are MIT licensed. Did I miss something?

Also not clear: I can build ARM AARCH64 deb bundles; but I don't have access to an x64 box on which to generate x64 bundles.

**Comment by mikeoliphant** [comment]
Licenses aside, if it still is useful to you to have a .deb package I would be happy to accept a PR. It is something I thought about doing, but haven't gotten around to.

**Comment by mikeoliphant** [comment]
I've added deb packaging. Currently is is just for the default ubuntu build (so "amd64").
