### ISSUE TITLE
Fails with undefined symbol on armv71

### ISSUE THREAD

**Issue by riban-bw** [mikeoliphant/neural-amp-modeler-lv2#22]
I followed the build instructions for Linux (followed by `make install`) on a Raspberry Pi 4 running Debian Buster (32-bit) and the LV2 plugin was built without error (just several warnings). When launching with `jalv http://github.com/mikeoliphant/neural-amp-modeler-lv2` I get an error:

`lilv_lib_open(): error: Failed to open library /usr/lib/lv2/neural_amp_modeler.lv2/neural_amp_modeler.so (/usr/lib/lv2/neural_amp_modeler.lv2/neural_amp_modeler.so: undefined symbol: _ZNSt10filesystem6statusERKNS_7__cxx114pathE)`

This is built from "main" branch 207777e.

Compiled with gcc 8.3.0. This may require `-lstdc++fs` linker option.

**Comment by mikeoliphant** [comment]
> Compiled with gcc 8.3.0. This may require `-lstdc++fs` linker option.

Yeah, that is what that error looks like.

I added it to the CMake link libraries, so it shouldn't be a problem going forward.

**Comment by riban-bw** [comment]
Thanks for the prompt response and fix. I wonder if it needs to be there for all builds and whether it has any detrimental effect when not required, e.g. the plugin builds fine on Bullseye on aarch64. FYI we won't be able to use it with Zynthian at the moment because it xruns on the 32-bit Buster image we use (maybe due to other limitations in the Zynthian software). Many thanks for fixing this. It was fun playing with it on my aarch64 RPi400.

**Comment by mikeoliphant** [comment]
> I wonder if it needs to be there for all builds and whether it has any detrimental effect when not required,

I think having it be explicitly required is fine - it just doesn't seem to be necessary on new version of gcc.

> we won't be able to use it with Zynthian at the moment because it xruns on the 32-bit Buster image we use

Yeah, 64-bit gives a *significant* performance increase.

Keep in mind that there are three preset qualities for NAM models. Most of the ones you'll find are "standard" - which is the most expensive. I was able to run "feather" models (and maybe "lite" - I can't remember) on a 32-bit RPi4, though.

**Comment by mikeoliphant** [comment]
@riban-bw Btw, you can find some of the lightweight "feather" models here:

https://tonehunt.org/?tags=feather-mdl
