### ISSUE TITLE
How to load a model?

### ISSUE THREAD

**Issue by buscon** [mikeoliphant/neural-amp-modeler-lv2#23]
It might be a trivial question, but I do not find a way to do it.

How do you load a model?
I am loading neural-amp-modeler-lv2 in a carla rack, but I cannot find a way to load a model.

**Comment by rusk911** [comment]
the "gear" button for showing GUI for other plugins do open a model load window.


![Screenshot at 2023-05-17 15-26-41](https://github.com/mikeoliphant/neural-amp-modeler-lv2/assets/7164744/6c21f335-b76f-49c0-b1f1-ba66993004e8)

**Comment by buscon** [comment]
thanks for your answer.

If I click the "gear" button using carla rack as a standalone, it works as expected. But when I load carla rack as a plugin (whether vst or lv2) in Reaper, then nothing happens. 
Is this an already known problem?

**Comment by falkTX** [comment]
yes, this is sorta expected. when carla is a plugin, the DSP side is split and runs on the host/daw process.
I do not have a way to get a file dialog open in there for now.

you can try via https://github.com/DISTRHO/Ildaeil as that includes a file dialog for such plugins. might be a way to get it to run in reaper (which is silly, loading LV2 under an LV2 host...)

**Comment by buscon** [comment]
> yes, this is sorta expected. when carla is a plugin, the DSP side is split and runs on the host/daw process. I do not have a way to get a file dialog open in there for now.
> 
> you can try via https://github.com/DISTRHO/Ildaeil as that includes a file dialog for such plugins. might be a way to get it to run in reaper (which is silly, loading LV2 under an LV2 host...)

thanks for your answer, I will look into that.
