### ISSUE TITLE
Git clone does not download NeuralAmpModeler repo

### ISSUE THREAD

**Issue by 38github** [mikeoliphant/neural-amp-modeler-lv2#24]
I had to manually download it from the repo and extract to deps/ folder under neural-amp-modeler-lv2.

**Comment by 38github** [comment]
It seems none of the outside repos are downloaded.

**Comment by mikeoliphant** [comment]
You need to add "--recurse-submodules" when you clone it.

**Comment by 38github** [comment]
Oh, sorry,
