### ISSUE TITLE
ReLU activation result in unprocessed sound.

### ISSUE THREAD

**Issue by 38github** [mikeoliphant/neural-amp-modeler-lv2#26]
I have models that I have trained using ReLU activation but all I get is unprocessed sound. Is the plugin hard coded to use only FastTanh?

If so, can it be codec to use FastTanh with Tanh models but others, like ReLU, use their respective activation?

**Comment by mikeoliphant** [comment]
FatTanh is only used as an alternative to Tanh - ReLU should be unaffected.

Regardless, this is an issue for the NeuralAmpModelerCore repo - can you open it there?

**Comment by 38github** [comment]
I will try it out the coming day and report back.

**Comment by 38github** [comment]
Btw, if it is an issue in NeuralAmpModelerCore wouldn't NeuralAmpModelerPlugin also be affected by this? The models do work in that plugin.

**Comment by mikeoliphant** [comment]
> Btw, if it is an issue in NeuralAmpModelerCore wouldn't NeuralAmpModelerPlugin also be affected by this?

Yes. That's strange. The LV2 plugin and the VST plugin shouldn't differ with respect to this behavior - all of the relevant code is in NeuralAmpModelerCore.

**Comment by 38github** [comment]
I will try them all out hopefully tomorrow. It is 10:00 P.M. here so I will likely listen to some music and watch some shows the remaining hours.

**Comment by 38github** [comment]
I did an updated compile and it seems that it is working correctly. My earlier version was not that old but I am glad that it was just a simple compile that was needed.
