### ISSUE TITLE
Building for MOD

### ISSUE THREAD

**Issue by mikeoliphant** [mikeoliphant/neural-amp-modeler-lv2#29]
@falkTX I'm having trouble building using mod-plugin-builder.

I'm getting errors handling **std::filesystem**:

```
/home/oliphant/mod-workdir/moddwarf/build/neural-amp-modeler-lv2-8ea9157743c0b95995f5253e2a18e95fbe7cbb34/deps/NeuralAmpModelerCore/NAM/dsp.h:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
```

It seems you are using a pretty old compiler? I specify targeting c++17 in the CMakefile:

`target_compile_features(neural_amp_modeler PUBLIC cxx_std_17)`

I get `-std=c++1z` on the compile commandline.

You've built the plugin for mod, correct? Are you using a different environment than the stock mod-plugin-builder?

**Comment by falkTX** [comment]
you are using "moddwarf" target, which only supports up to C++14 because it uses gcc7.
you need to use "moddwarf-new" target, which uses gcc9

**Comment by mikeoliphant** [comment]
Thanks - that seems to have worked.

With the "minimal" bootstrap, I'm assuming I will need to push manually?

As in this example from the mod-plugin-builder readme:

`tar czf bundle1.lv2 bundle2.lv2 | base64 | curl -F 'package=@-' http://192.168.51.1/sdk/install; echo`

**Comment by falkTX** [comment]
you always push manually. the curl based approach is easiest and you can even put it as some cmake target thing, or script it.
if building as MPB package the plugins end up in `~/mod-workdir/moddwarf/plugins`

**Comment by mikeoliphant** [comment]
By "manual" I just meant using curl rather than using `./build` to publish. I thought `./build` wasn't working, but I was just specifying the wrong platform.

**Comment by falkTX** [comment]
the "./build" is only really relevant for plugins that are ready and meant to be either built for local usage or to be built on the cloud.
pushing to a git repo, updating hash and rebuilding is just too time consuming, so it is not a recommended approach during development.

the "source local.env moddwarf-new" method is there to allow to setup the current environment for MOD builds, I suggest to use that initially.

**Comment by mikeoliphant** [comment]
Closing, since I've got this working.
