### ISSUE TITLE
Support input gain and output volume controls

### ISSUE THREAD

**Issue by mikeoliphant** [mikeoliphant/neural-amp-modeler-lv2#3]
Add control ports for input gain and output volume.

**Comment by mikeoliphant** [comment]
This is mostly resolved, but since it is using LV2 control ports, it per-sample-buffer and not per-sample accurate. Using LV2 parameters would be better.

**Comment by falkTX** [comment]
hosts will split the audio cycle into multiple parts as needed, so lv2 params is not always necessary.
some parameter smoothing is likely to be enough here, I dont suppose many people will be automating these specific controls
