### ISSUE TITLE
Publishing this plugin on Flathub: You or me? :)

### ISSUE THREAD

**Issue by runiq** [mikeoliphant/neural-amp-modeler-lv2#33]
Like I mentioned [before](https://github.com/mikeoliphant/neural-amp-modeler-lv2/pull/30), I'm trying to build your plugin as a Flatpak so I can use it with Flatpak'd Ardour and friends. I've gotten a first working version [here](https://gitlab.com/runiq/org.freedesktop.linuxaudio.plugins.neuralampmodelerlv2).

Before I go ahead and upload your plugin to Flathub, I would like to ask if you want to do it yourself (in accordance with [Flathub's submission guidelines](https://github.com/flathub/flathub/wiki/App-Submission#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer)). There are a few [requirements](https://github.com/flathub/flathub/wiki/App-Requirements), but they can easily be met, seeing how [lots of other audio plugins are already on Flathub](https://github.com/search?q=repo%3Aflathub%2Forg.freedesktop.LinuxAudio.BaseExtension+org%3Aflathub+org.freedesktop.LinuxAudio&type=repositories).

**Comment by runiq** [comment]
I'm not sure, but I'm fairly confident it can. Haven't ever had to deal with GH actions, to be honest.

**Comment by mikeoliphant** [comment]
How about you go ahead and get it set up. If I get more established released going at some point, it might make sense to try to integrate it more then.

**Comment by runiq** [comment]
Great, I will! Flathub also have some [Github actions](https://github.com/flatpak/flatpak-github-actions) available. I have yet to find out if they help with publishing, though.

**Comment by mikeoliphant** [comment]
👍

**Comment by runiq** [comment]
I'm going through the requirements and almost everything looks good. There's just one little thing: [Flathub only allows publishing Git tags](https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds).

Would you consider tagging a commit?

**Comment by mikeoliphant** [comment]
Ok, I cut a release and generated a tag.

**Comment by runiq** [comment]
Alright, done: https://github.com/flathub/flathub/pull/4271

**Comment by mikeoliphant** [comment]
👍

**Comment by runiq** [comment]
[Okay, done](https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.NeuralAmpModeler). I'll ask them to make you a maintainer for that repo as well, so you can merge PRs etc.

Whenever you publish a new release in _this here_ repo, a corresponding PR on the nam.lv2 _Flathub_ repo will be created by a bot. It currently has to be merged manually, but it can also be configured to auto-merge upon a successful build.

For everything else, see [the Flathub maintenance docs](https://docs.flathub.org/docs/for-app-authors/maintanance/). I'd be happy to maintain the Flatpak if you want, though.

**Comment by mikeoliphant** [comment]
Sounds good - thanks!
