### ISSUE TITLE
Illegal forge write in work_response.

### ISSUE THREAD

**Issue by rerdavies** [mikeoliphant/neural-amp-modeler-lv2#38]
Sorry I haven't been tracking as closely as I should.

There's a problem with calling `write_current_path` in `work_response`. 

The issue specifically is that `write_current_path` writes a message to the output forge, which is not in a valid state when handling `work_response`. The output forge is initialized at the start of process(), with 
```
    lv2_atom_forge_set_buffer(&atom_forge, (uint8_t*)ports.notify, ports.notify->atom.size);
   lv2_atom_forge_sequence_head(&atom_forge, &sequence_frame, uris.units_frame);
```
and closed off with 
```
    lv2_atom_forge_pop(&atom_forge, &sequence_frame);
```
which seems to have gone missing from current sources.

It is therefore invalid to use the atom_forge outside of process() call. The atom_forge will either be unintialized, or the sequence will be closed, depending on whether the scheduler callbacks occur before or after process().

Pull request forthcoming. It is dependent on pull request #37 having been merged first. If the merge breaks, let me know, and we'll work it out.

**Comment by rerdavies** [comment]
@falkTX : My previous pull request changed where currentModelPath gets set. It was set when the load completed; but is now set when the load request is initiated. (Avoids a bunch of problems synchronizing state.save() with property_Set).

Would it perhaps make more sense to call to trigger the call to write_current_path() when the load task is started as well? It would have to be done via a boolean flag as well, since the atom_forge is not available during Plugin::restore().

And while we're at it...  do your really want to send the message after receiving a patch_Set? The way I remember the requirements being described, the extra patch_set was supposed to be sent after state.restore(), but not after receiving a patch_Set. Current sources send the message in both cases.

**Comment by mikeoliphant** [comment]
I'm going to need to rely on some sort of consensus between the two of you on this.

From the plugin perspective, I just have a path that I want to expose via the host and save in the state...

To the extent that this does get sorted out in a way that everyone is happy with, it would be great if it could be documented somewhere so that the next guy that comes along and wants to do this has a fighting chance.

**Comment by rerdavies** [comment]
I completely agree.  Although I'd suggest we have that discussion on #36, which definitely needs @falkTX 's input, just to keep the discussion focused for those that follow.

I think this fix is pretty uncontroversial. (And rather urgent because of the missing `lv2_atom_forge_pop` call).

**Comment by rerdavies** [comment]
After reviewing sample code and LV2 sample files, it's clear that the second pull request can be discarded. 

Host MUST process plugins in the following order:

1. Call run.
2. Make scheduler callbacks.
3. Process the output buffer.

Plugins need not pop the frame to update the length of the atom sequence.

Please reject Pull request #39.
