### ISSUE TITLE
trouble building with gcc 13.1.1

### ISSUE THREAD

**Issue by kevin-nel** [mikeoliphant/neural-amp-modeler-lv2#43]
Hi, I'm on fedora 38 trying to compile the plugin.
when I try to load it using carla I get 
```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.32' not found required by /home/xxx/.lv2/neural_amp_modeler.lv2/neural_amp_modeler.so
```

I am using the latest version of gcc (13.1.1) and running `strings /usr/lib/libstdc++.so.6 | grep GLIBCXX`
returns the following:

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
...
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_3.4.31
*GLIBCXX_3.4.32*
GLIBCXX_TUNABLES
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
so I do have it.
If there is something I am missing or something I can change in the Makefile I would appreciate assistance.

**Comment by mikeoliphant** [comment]
Are you maybe running carla in a different environment from where you compiled (inside a virtual environment like conda, for example)?

**Comment by kevin-nel** [comment]
thanks, Carla was a flatpak and I had compiled NAM normally. I see there is another issue to have a flatpak build which would be nice. but this is working for me now thank you!

**Comment by mikeoliphant** [comment]
👍
