### ISSUE TITLE
nam plugin doesn't see models

### ISSUE THREAD

**Issue by ValentinSvidrigaylov** [mikeoliphant/neural-amp-modeler-lv2#49]
Sup, recently discovered nam and then this awesome plugin. Everything looks awesome except that plugin doesn't see any models I load  (running patchbox modep module on raspberry pi 4). Maybe I'm using wrong directory or something (I've tried uploading models to different folders but that didn't work).
All folders:
![chrome_0OSZ1HYRw8](https://github.com/mikeoliphant/neural-amp-modeler-lv2/assets/73439701/352c7e48-00d1-4963-be54-cfd0037ef49c)

**Comment by mikeoliphant** [comment]
That's an issue with your modep. You need to have a version that has support for nam model files.

**Comment by ValentinSvidrigaylov** [comment]
> That's an issue with your modep. You need to have a version that has support for nam model files.

Yeah, thanks for answer, resolved by adding folder to user-files (also there is a topic about that https://community.blokas.io/t/please-add-the-nam-models-directory/4584/5).

**Comment by mikeoliphant** [comment]
👍
