### ISSUE TITLE
Plugin causes crashes (x86_64 Linux)

### ISSUE THREAD

**Issue by 38github** [mikeoliphant/neural-amp-modeler-lv2#50]
REAPER (x86_64, OpenSUSE Slowroll) crashes using both git20231010 and git20231019 builds. I have tried both GCC 13 and Clang 17 but it happens with all of them. I got no useful information in the terminal that can help us. I have also tried both REAPER 6.83 and 7.001.

EDIT: Also crashes Ardour 7.5

**Comment by mikeoliphant** [comment]
Not sure what you mean by "git20231010". If you can isolate which commit caused the problem to start, that would be helpful.

Does the latest release version work for you?

Does it crash when you add the plugin with no model loaded, or just when you load a model (or load a preset with a model loaded)?

**Comment by 38github** [comment]
Sorry. It appears that a compile flag caused this. I am sorry for taking up your time.

**Comment by 38github** [comment]
Trying out openMP (maybe doesn't do anything spped wise) with GCC was ok but with Clang it caused all this.

**Comment by mikeoliphant** [comment]
Yeah, clang seems to do a better job of optimizing the underlying matrix operations.

The crash might be the compiler adding vectorization that your CPU doesn't support.

**Comment by 38github** [comment]
Thank you for taking your time and I will do my best to not rush an ISSUE before I have thoroughly tested my setup. I am sorry for that.

**Comment by mikeoliphant** [comment]
No worries.
