### ISSUE TITLE
LV2 crashes Reaper

### ISSUE THREAD

**Issue by gitthedroid** [mikeoliphant/neural-amp-modeler-lv2#52]
The LV2 crashes REAPER 7.0.6 when it is added to a track!
I did the build with CMAKE and then copied the folder ~/neural-amp-modeler-lv2/build/neural_amp_modeler.lv2 to ~/.lv2. REAPER loaded the LV2 which was seen in the FX window as a new plugin. When double clicked to add the FX to a track, REAPER crashed.

If there are possible log files I can provide please point me to the right location!

Waiting to NAM out,

                                      gitthedroid

**Comment by gitthedroid** [comment]
Platform is Ubuntu Studio 22.04.3

**Comment by mikeoliphant** [comment]
What processor does your computer have? If it is older and doesn't support modern optimizations, you may need to add "-DUSE_NATIVE_ARCH=OFF" to your cmake command line.

**Comment by gitthedroid** [comment]
It is an older I3. It also crashed Ardour 6.9. I will set flags to off. I will also try a build on a Jetson Nano. This is my initial build for NAM LV2.  My target build will be on the studio MSI  510i Pro WiFi with 10th gen I5. Proceeding to rebuild.

**Comment by gitthedroid** [comment]
I recompiled with your option before the .. cmake argument. It loaded in REAPER fine with no GUI. I will finish testing after dinner. Thanx very much for your assistance!
