### ISSUE TITLE
REAPER, cpu still consumption after unarmed

### ISSUE THREAD

**Issue by llj098** [mikeoliphant/neural-amp-modeler-lv2#54]
Hello, 

I'm using the Reaper(7.0.7)+NAM-lv2,ALSA, installed by AUR, version: 0.1.3.r14.43fb036

I found that after the track is unarmed, the cpu still very high, I must shut down all the plugins(FX button) the cpu usage will go down.

I also use reaper+nam-vst on macos, the cpu cools down just after I unarm the track. 

So the behavior is different. is this by design or something goes wrong? 

Thanks.

**Comment by mikeoliphant** [comment]
I believe this is DAW-dependent behavior and is by design - the plugin processing is still called even though the track is not armed.

I see the same behavior with other VSTs (including the official NAM plugin) in Reaper on Windows.
