### ISSUE TITLE
very cool project.  would be sick if BYOD allowed lv2 plugins but this works great as is

### ISSUE THREAD

**Issue by billyblackburn** [mikeoliphant/neural-amp-modeler-lv2#56]
this is my fav plugin ever.  and thats saying alkot!!!!!!!!!!!!!!!!!

**Comment by mikeoliphant** [comment]
Glad you are enjoying it!

**Comment by billyblackburn** [comment]
Is there a way we can make a GUI for the Linux version? I'm jealous of the windows and Mac plugin

**Comment by mikeoliphant** [comment]
That isn't something I am interested in doing. If you are interested in a version that has a GUI, I suggest checking out the MOD desktop app: https://github.com/moddevices/mod-desktop-app

**Comment by brummer10** [comment]
I'm made  GUI for it using libxputty:
![2024-01-30_18-09](https://github.com/mikeoliphant/neural-amp-modeler-lv2/assets/2683982/37610d8c-6206-4cd1-83b3-3e1cf9380b9a)


If there is a interest I could contribute it to the project. 
Otherwise it could be used as well as extra installed GUI. Works so far in Ardour, jalv and carla. 
Just for Reaper it needs to be part of the original bundle.  
Somehow it didn't work in Qtractor, I've no idea why.

**Comment by mikeoliphant** [comment]
Hi @brummer10 - fan of your work on guitarix and related stuff!

I appreciate the offer, but I'm trying to keep this repo as simple as possible, and I really don't want to be maintaining GUI code.

You are more than welcome to make it available as a fork (or, even better, using this repo as a submodule - if that's possible).

**Comment by billyblackburn** [comment]
Ok I wasn't aware of the mod desktop app.  That libxputty guy looked cool too...Ill try the mod app once I get home and probably all day tomorrow :)

**Comment by brummer10** [comment]
Thanks @mikeoliphant nice to hear that.
So I've created a repository for the GUI. It didn't require a fork or a submodule at all. 
It just require that the neural-amp-modeler from your repository is installed already. 
It could then be installed as add-on. 
The repository is here:
https://github.com/brummer10/neural-amp-modeler-ui

regards
hermann

**Comment by mikeoliphant** [comment]
Great! I added a link to it in the repo README.

**Comment by brummer10** [comment]
Thanks. I hope it will turn out to be useful.
