### ISSUE TITLE
warning: Writing ambiguous atom:Path literal.

### ISSUE THREAD

**Issue by brummer10** [mikeoliphant/neural-amp-modeler-lv2#58]
When neural-amp-modeler receive a patchGet message it sends write_current_path() without check if there is a patch loaded or not, that result, in case no patch is loaded in a empty path message. 
jalv.gtk-d response with a warning

```
warning: Relative path but base is not a file URI.
warning: Writing ambiguous atom:Path literal.

```
a simple check if currentModelPath.empty() before response could avoid that.

This warning appears on any startup with empty path, regardless if  a custom UI ask for the path or not.

**Comment by mikeoliphant** [comment]
Not sure why an empty path isn't valid. How else would you let the host know that there isn't a model loaded?

**Comment by brummer10** [comment]
Just did a quick test, and indeed hosts seems to expect a empty path in order to know that no model is loaded, otherwise they assume that the last pathSet message was successful.
So it seems it's jalv here to blame for print a warning for a valid message.

**Comment by mikeoliphant** [comment]
With LV2 it seems like it is often hard to know what is "correct" - both hosts and plugins seem to mostly just be trying to do what the other expects as best they can...
