### ISSUE TITLE
[Feature Request] Switch profiles using midi

### ISSUE THREAD

**Issue by Maxinova** [mikeoliphant/neural-amp-modeler-lv2#59]
Currently, only input and output volume settings can be configured using a midi input in a daw, but not the amp profile.

Could it be possible to implement a way to change between installed profiles using a midi input? I can see two approaches:

- Assigning a midi input to select the next or previous profile in the loaded bank.
- Listing all profiles in the profile bank and assigning them a range of values between 0 and 255. This way, it would be possible to use a midi slider or knob to quickly select a profile from those available.

I'm using Linux, and I tried in two VST hosts : Carla and Element

**Comment by mikeoliphant** [comment]
This seems like functionality that should be the purview of the host. Can you save presets and select them based on midi input? I'm pretty sure that is possible in some hosts.

**Comment by mikeoliphant** [comment]
It seems like a logical feature for something like Element, since it is live-performance focused.

**Comment by mikeoliphant** [comment]
https://element.readthedocs.io/en/latest/chapters/ui/graph-options.html#switching-graphs

**Comment by Maxinova** [comment]
Thanks!
It could be working, but I don't really understand the graph and nested graph system on Element at the moment. I'm gonna check this out. Thanks for the help!
