### ISSUE TITLE
[FEATURE REQUEST] Downmix input to one channel?

### ISSUE THREAD

**Issue by 38github** [mikeoliphant/neural-amp-modeler-lv2#6]
I noticed that in DAWs that send a stereo signal to plugins even though the track has mono audio I get unprocessed audio in the left channel and processed in the right.

**Comment by 38github** [comment]
Would making it having a stereo input that is downmixed to mono internally carry any negatives things with?

**Comment by mikeoliphant** [comment]
It would add a bit of overhead, but not much. My larger concern is that the plugin *is* mono. Exposing it as a stereo plugin doesn't really make sense.

**Comment by 38github** [comment]
I see. Thank you for your help.
