### ISSUE TITLE
96/192 kHz models are severely high passed

### ISSUE THREAD

**Issue by 38github** [mikeoliphant/neural-amp-modeler-lv2#62]
I noticed that models that are 96/192 kHz are severely high passed compared to the official NAM VST3. The attached files was rendered at 192kHz and then resampled down to 48 kHz AAC/MP4.

First half is VST3 and second one is LV2 (win64):

https://github.com/mikeoliphant/neural-amp-modeler-lv2/assets/18294149/7caaa97c-96b5-4a19-8dc6-7a3f61e9481d

Model used:
[lstm-192khz.nam.zip](https://github.com/mikeoliphant/neural-amp-modeler-lv2/files/14915901/lstm-192khz.nam.zip)

Update: No model is needed to be loaded to achieve the high pass.

**Comment by mikeoliphant** [comment]
That's likely the DC blocker (which correct the model's DC offset). The coefficient should be based on the sample rate.

**Comment by mikeoliphant** [comment]
Can you try the latest version? I just made a change to adjust the dc blocker coefficient based on sample rate. It should be mostly the same (actually a bit less aggressive) at 48k, but much less aggressive at higher rates.

**Comment by 38github** [comment]
> Can you try the latest version? I just made a change to adjust the dc blocker coefficient based on sample rate. It should be mostly the same (actually a bit less aggressive) at 48k, but much less aggressive at higher rates.

Great job! Is it possible to lower it somewhat more without dc happening? I feel pretty certain that I hear the very lowest of lows are taken out at 96/192 when I use EQ models.

**Comment by 38github** [comment]
I don't know how to properly measure or visualize these very low frequencies so all I can do is listen and do changes. This might lead to placebo effect but I believe that `float dcBlockCoefficient = 1 - (55.0 / sampleRate);`retains most of the very lows at 192 kHz. At 48 kHz I feel certain that I do not hear a difference.If this value is effective against DC I don't know.

Please correct my assumptions and possible placebos.

**Comment by mikeoliphant** [comment]
There are a couple of things that can be done to actually measure things.

To compare the lv2 with the official NAM plugin, you can run the same audio through both and null test them. To do that, you subtract one from the other and then look at the frequency spectrum of the diff.

To measure the impact of the lv2 dc blocker, you would want to run full spectrum noise through the plugin with no model loaded and see what effect it has. If the impacted low frequency range is larger at higher sample rates, then my coefficient scaling isn't working correctly.

**Comment by 38github** [comment]
> There are a couple of things that can be done to actually measure things.
> 
> To compare the lv2 with the official NAM plugin, you can run the same audio through both and null test them. To do that, you subtract one from the other and then look at the frequency spectrum of the diff.
> 
> To measure the impact of the lv2 dc blocker, you would want to run full spectrum noise through the plugin with no model loaded and see what effect it has. If the impacted low frequency range is larger at higher sample rates, then my coefficient scaling isn't working correctly.

I will probably do a null test soon and in the mean time I will continue using the value 55.0 and see if I get any DC issues. I will let you know when I have done any comparisons. Regards.

**Comment by mikeoliphant** [comment]
Btw, checking for DC offset is easy. Just look at the resulting waveform and see if it is centered on zero or not.

**Comment by mikeoliphant** [comment]
I did some frequency analysis, and the dc blocker is definitely cutting out more low end than I'd like. I'll look into alternatives.

**Comment by mikeoliphant** [comment]
Strangely, I'm not seeing DC offsets now even with the DC blocker code completely removed.

It definitely *used* to be a problem:

https://github.com/mikeoliphant/neural-amp-modeler-lv2/issues/41

**Comment by 38github** [comment]
> Strangely, I'm not seeing DC offsets now even with the DC blocker code completely removed.
> 
> It definitely _used_ to be a problem:
> 
> #41

Interesting! I will try it with many different LSTM settings (num_layers_, hidden_size, etc) and see if I get any issues.

**Comment by mikeoliphant** [comment]
I'm seeing the same behavior (no DC offset even with DC offset correction code removed) in the official NAM plugin.

**Comment by mikeoliphant** [comment]
I tried with a really old version of the lv2 plugin, and I *still* couldn't get a DC offset to happen. Maybe I'm just not trying the right models (although I recall the issue being pretty pervasive). If you can get a DC offset, please share the model.

**Comment by 38github** [comment]
> I tried with a really old version of the lv2 plugin, and I _still_ couldn't get a DC offset to happen. Maybe I'm just not trying the right models (although I recall the issue being pretty pervasive). If you can get a DC offset, please share the model.

I will do that!

**Comment by 38github** [comment]
I haven't experienced any DC issues yet with a value of 25.0. I am interested though in what I need to change to disable it completely like you mentioned.

**Comment by mikeoliphant** [comment]
You just need to comment out the whole DC blocker loop:

https://github.com/mikeoliphant/neural-amp-modeler-lv2/blob/72fd4a1e3d6118f52be7f609708209535e8a9e24/src/nam_plugin.cpp#L293-L302

**Comment by 38github** [comment]
> You just need to comment out the whole DC blocker loop:
> 
> https://github.com/mikeoliphant/neural-amp-modeler-lv2/blob/72fd4a1e3d6118f52be7f609708209535e8a9e24/src/nam_plugin.cpp#L293-L302

Thank you once again!

**Comment by 38github** [comment]
The current settings affect the low frequencies too much in my opinion. Try nulling a model loaded in neural-amp-modeler-lv2 against the captured file. Now also try the same model with with e.g. Ratatouille lv2 or the official plugin.

**Comment by mikeoliphant** [comment]
I'd been planning to revisit this once I had a model that was showing dc offset issues so that I could see what (if any) trade-off a subtler high pass has. I haven't been able to find a model that has dc offset issues, though.

I may just remove the dc blocker all together.

**Comment by mikeoliphant** [comment]
I went ahead and removed the dc blocker, since it seemed to be doing more harm than good.
