### ISSUE TITLE
libstdc++.so.6: version `CXXABI_1.3.15' not found 

### ISSUE THREAD

**Issue by youpi-ck** [mikeoliphant/neural-amp-modeler-lv2#66]
Hello,

When attempting to load your plugin into Carla, I encounter the following error:

![image](https://github.com/mikeoliphant/neural-amp-modeler-lv2/assets/95099899/32f3d7f8-8920-4f14-839e-1eaa53f334a5)

'I have noticed that this might be due to the fact that my libstdc++.so.6 is located in the /lib64 folder.

For context, I am using Fedora.

Is this a bug, or is there something I need to do to resolve the issue?'

Thank you

**Comment by youpi-ck** [comment]
Okay, so I wrote this a bit too quickly. It's a problem from the Flatpak version of Carla.

**Comment by mikeoliphant** [comment]
Yep - it is an issue with Flatpaks and plugins that were built under different conditions.

I assuming you were building the NAM LV2 plugin yourself? There is a Flatpak version of the plugin available (although it may be a bit out of date).
