### ISSUE TITLE
would it be possible to use the below two projects to make a GUI?

### ISSUE THREAD

**Issue by RustoMCSpit** [mikeoliphant/neural-amp-modeler-lv2#67]
https://github.com/brummer10/Ratatouille.lv2
for ratatouille, the Neural-Amp-Modeler and the RTNeural loaders into self contained C++ classes it wont be to hard to reuse them in other projects. Same is true for the convolver class and the dcblocker.

https://github.com/Chowdhury-DSP/BYOD
for BYOD, there is a signal chain type GUI that already accepts IRs and will just need to accept NAM files

**Comment by mikeoliphant** [comment]
@brummer10 (who made Ratatouille) already has a GUI here:

https://github.com/brummer10/neural-amp-modeler-ui

I have no plans to add GUI code to this repository.

**Comment by RustoMCSpit** [comment]
whats the use case of this vs ratotouille?
