### ISSUE TITLE
No surces given to target: neural_amp_modeler

### ISSUE THREAD

**Issue by KaiggaShaw** [mikeoliphant/neural-amp-modeler-lv2#71]
![1](https://github.com/user-attachments/assets/460f28a9-15a5-4686-b254-f4b29e728f22)

When I run "cmake .. -DCMAKE_BUILD_TYPE="Release"   in my raspberrypi

![QQ20241008-055845](https://github.com/user-attachments/assets/4b4cb982-51e1-4027-a72a-98d7203ed5d7)

Thanks so much!

**Comment by KaiggaShaw** [comment]
> 您可能在克隆存储库时没有添加“--recurse-submodules”，因此您没有子模块。

thanks so much! Then how can I use it after bulding. This is my first time to use linux,sorry to bother you! I just connected raspberrypi with sound card.
![3](https://github.com/user-attachments/assets/c1050159-b89d-4960-af9f-a6f708d6da35)

**Comment by mikeoliphant** [comment]
You need an LV2 host application, such as a DAW.
