### ISSUE TITLE
No support for aidax files?

### ISSUE THREAD

**Issue by brummer10** [mikeoliphant/neural-amp-modeler-lv2#74]
Hi
I just testet your latest implementation of rtneural support, which is great to have.
Loading files ending with .json works fine. 
Just, files ending with .aidax didn't work. 
That means, the plug didn't response with load file is failing "None", 
it response with "Staging model change", but, it didn't sound as if it works. 
When I rename the aidax files to json it works as expected.

**Comment by mikeoliphant** [comment]
Thanks for letting me know - I'll add that extension.

**Comment by mikeoliphant** [comment]
Fixed.

**Comment by brummer10** [comment]
Nice, so I'll update the GUI to reflect that.

**Comment by mikeoliphant** [comment]
👍

**Comment by brummer10** [comment]
Yep, I've seen that. Nice. 
Still, currently I can't see any advance on using rtneural for NAM models. More in opposite I found some NAM models which heavily increase dsp load with your latest version. Mainly nearly all models from here:
https://github.com/pelennor2170/NAM_models

**Comment by mikeoliphant** [comment]
For LSTM the situation is a lot clearer. My RTNeural implementation is way faster than the NAM implmentation.
