### ISSUE TITLE
optimisation didn't fetch

### ISSUE THREAD

**Issue by brummer10** [mikeoliphant/neural-amp-modeler-lv2#75]
Hi
I've real difficulty to get the optimisation to take place. Regardless what I try, the  "-march=x86-64-v3" didn't take place in the NeuralAudio stage. Only, after I edit the CMakeLists.txt file there and add 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=x86-64-v3")`
on top of the file, I get the desired result with the old performance. 

Seems to me the very same is true for the flags
LSTM_PREFER_NAM and WAVENET_PREFER_NAM.

I use `-DCMAKE_VERBOSE_MAKEFILE=ON` to view what's going on.

**Comment by mikeoliphant** [comment]
Ok, I'll look into it.

My understanding is that CMake compiler flags *should* cascade down to submodules, but it is certainly possible that it isn't working.

**Comment by mikeoliphant** [comment]
The LSTM_PREFER_NAM and WAVENET_PREFER_NAM flags are working - they are actually flags for the neural-amp-modeler-lv2 code, not the NeuralAudio code. The preference for NAM/RTNeural in NeuralAudio is done at runtime.

The  "-march=x86-64-v3" definitely doesn't seem to be propagating down, though.

**Comment by brummer10** [comment]
I've not much experience with CMake, I'm used to use plain make. 
The LSTM_PREFER_NAM and WAVENET_PREFER_NAM flags was just my first guess when I noticed the high dsp load and I tried to propagate them to NeuralAudio submodule as I guessed that would be the reson for it. But now, with the  x86-64-v3 flag solved (for my build) I see that they aren't needed in 99%. 

Really good job, I'll keep a eye on it.

**Comment by mikeoliphant** [comment]
I just pushed a fix for the native arch flag.

**Comment by mikeoliphant** [comment]
Just did some testing on Raspberry Pi - RTNeural is *way* slower there. Not sure why.

**Comment by 38github** [comment]
I tried cmake .. ‑DUSE_NATIVE_ARCH=ON -DCMAKE_BUILD_TYPE=Release but got:
```
CMake Warning:
  Ignoring extra path from command line:

   "‑DUSE_NATIVE_ARCH=ON"
```

I therefore continued with my exported flags e.g. -Ofast -flto -fopenmp-simd and RTNeural still uses more CPU like before.

**Comment by mikeoliphant** [comment]
Not sure what is happening there.

**Comment by brummer10** [comment]
> I tried cmake .. ‑DUSE_NATIVE_ARCH=ON -DCMAKE_BUILD_TYPE=Release but got:
> 
> ```
> CMake Warning:
>   Ignoring extra path from command line:
> 
>    "‑DUSE_NATIVE_ARCH=ON"
> ```
> 
> I therefore continued with my exported flags e.g. -Ofast -flto -fopenmp-simd and RTNeural still uses more CPU like before.

That happen when you copy the command from the website. Try typing it in your terminal by hand and it works. 
Copy command-line args from a website may contain invisible signs!!

**Comment by brummer10** [comment]
Can confirm that the build flag options works with the latest revision. 
I tend to use NAM for wavenet for now as it uses less CPU here. I got around 9.2% dsp load with rtneural and around 7.2% with NAM for the same model file. 
I also noted a lot of warnings during build using gcc 13.3
using clang++ (16.6) makes it freeze my box when load a NAM wavenet file.

**Comment by brummer10** [comment]
Demoing what you get when you copy  ‑DUSE_NATIVE_ARCH=ON from the site:
`echo ‑DUSE_NATIVE_ARCH=ON | cat -v`
M-bM-^@M-^QDUSE_NATIVE_ARCH=ON

and when you type it:
`echo -DUSE_NATIVE_ARCH=ON | cat -v`
-DUSE_NATIVE_ARCH=ON

**Comment by 38github** [comment]
> Demoing what you get when you copy ‑DUSE_NATIVE_ARCH=ON from the site: `echo ‑DUSE_NATIVE_ARCH=ON | cat -v` M-bM-^@M-^QDUSE_NATIVE_ARCH=ON
> 
> and when you type it: `echo -DUSE_NATIVE_ARCH=ON | cat -v` -DUSE_NATIVE_ARCH=ON

Thank you for the demonstration! Very helpful!

**Comment by mikeoliphant** [comment]
> That happen when you copy the command from the website. Try typing it in your terminal by hand and it works. Copy command-line args from a website may contain invisible signs!!

I'm doing a bit of trickery because github's markdown was eating the '-'. Maybe I'll put it in a code block.

**Comment by mikeoliphant** [comment]
> I tend to use NAM for wavenet for now as it uses less CPU here. I got around 9.2% dsp load with rtneural and around 7.2% with NAM for the same model file. I also noted a lot of warnings during build using gcc 13.3 using clang++ (16.6) makes it freeze my box when load a NAM wavenet file.

It seems to be very platform and compiler dependent.

For me, RTNeural WaveNet is just *slightly* slower (Visual Studio, Windows x64) using both MSVC and Clang under VS. LSTM is about 2x faster.

Using gcc on Raspberry Pi, RTNeural is much slower for both WaveNet and LSTM.

I may switch the default in NeuralAudio to be NAM for WaveNet - at least for now.

Btw, if you add "-DBUILD_UTILS=ON" to your cmake commandline, it will build a program under the NeualAudio "Utils" folder that does a simple benchmark of RTNeural vs NAM for WaveNet and LSTM.

**Comment by brummer10** [comment]
> Btw, if you add "-DBUILD_UTILS=ON" to your cmake commandline, it will build a program under the NeualAudio "Utils" folder that does a simple benchmark of RTNeural vs NAM for WaveNet and LSTM.

Nice. 
I'm on linux debian sid with gcc 13.2.0 on a  Intel Core i5-7400, getting the following results:
NAM Test
RTNeural: 0.118036
Nam: 0.106075
RTNeural is: 0.89867x
LSTM Test
RTNeural: 0.00836338
Nam: 0.00864567
RTNeural is: 1.03375x

when using clang++ (16.0.6) I get:
NAM Test
RTNeural: 0.136336
Nam: 0.105817
RTNeural is: 0.776145x
LSTM Test
RTNeural: 0.00849865
Nam: 0.00961597
RTNeural is: 1.13147x

**Comment by brummer10** [comment]
btw. I noticed during rebuilds that make clean didn't work. Configure the CMake instructions only take place when I delete anything in /build (except .gitignore), otherwise it will use the old CMake configure line.
(All tests with optimisation switched on)
