### ISSUE TITLE
NAM file not loaded when project is reopened

### ISSUE THREAD

**Issue by 38github** [mikeoliphant/neural-amp-modeler-lv2#8]
I have tried in both Ardour7 and Qtractor with a git compile of this plugin from the last hour. I need to select file again when I reopen a saved project.

**Comment by mikeoliphant** [comment]
Yeah - I haven't implemented plugin save state yet. Issue opened here:

https://github.com/mikeoliphant/neural-amp-modeler-lv2/issues/9
